// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFEUa3cZQP8PGx33Y-XhKRbCTh3_6Fyc',
    appId: '1:931853293854:web:ce114e9bf7a7867abcd10f',
    messagingSenderId: '931853293854',
    projectId: 'locario-events',
    authDomain: 'locario-events.firebaseapp.com',
    storageBucket: 'locario-events.firebasestorage.app',
    measurementId: 'G-VZ52Z6RZQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjolWJUNisFnunNXEgoe5Xo1K-8TV_kA',
    appId: '1:931853293854:android:d6ceba32d4c6ce4bbcd10f',
    messagingSenderId: '931853293854',
    projectId: 'locario-events',
    storageBucket: 'locario-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeUrtHEUmePi3O-p3Z8BeSHwwpyEB0-WM',
    appId: '1:931853293854:ios:3b810a5939f6cb28bcd10f',
    messagingSenderId: '931853293854',
    projectId: 'locario-events',
    storageBucket: 'locario-events.firebasestorage.app',
    iosBundleId: 'com.example.locario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeUrtHEUmePi3O-p3Z8BeSHwwpyEB0-WM',
    appId: '1:931853293854:ios:3b810a5939f6cb28bcd10f',
    messagingSenderId: '931853293854',
    projectId: 'locario-events',
    storageBucket: 'locario-events.firebasestorage.app',
    iosBundleId: 'com.example.locario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPFEUa3cZQP8PGx33Y-XhKRbCTh3_6Fyc',
    appId: '1:931853293854:web:64ad463941d01dcfbcd10f',
    messagingSenderId: '931853293854',
    projectId: 'locario-events',
    authDomain: 'locario-events.firebaseapp.com',
    storageBucket: 'locario-events.firebasestorage.app',
    measurementId: 'G-1PYWD2X092',
  );
}
